SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, RR.REVIEW_DATE
FROM (SELECT COUNT(*), MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1) T
JOIN MEMBER_PROFILE MP ON MP.MEMBER_ID = T.MEMBER_ID
JOIN REST_REVIEW RR ON RR.MEMBER_ID = MP.MEMBER_ID
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;